import { Markdown } from "./Markdown";

const COMPARISON_MD = [
    "JSON transformation is a crowded space. `transon`'s bet is that **templates are themselves pure JSON** — storable, generatable, diff-able, and extensible with your own rules — traded against the terseness of a string DSL. Pick the tool that fits the job:",
    "",
    "| Tool | Template / language | Extensible | Deps & runtime | Best when |",
    "|---|---|---|---|---|",
    "| **transon** | pure JSON tree | custom rules, operators, functions | none (Python stdlib) | templates must be stored / generated / validated as JSON, with domain-specific rules, in Python |",
    "| [JSONata](https://jsonata.org/) | string expression DSL | limited | JS library | concise queries & expressions over JSON in JavaScript |",
    "| [jq](https://jqlang.github.io/jq/) | string filter language | limited | native binary | CLI piping and ad-hoc filtering in the shell |",
    "| [JSLT](https://github.com/schibsted/jslt) | string DSL (jq-like) | user functions | JVM | compact JSON→JSON on the JVM |",
    "| [Jolt](https://github.com/bazaarvoice/jolt) | JSON spec | limited | JVM | declarative structural reshaping on the JVM |",
    "| [JsonLogic](https://jsonlogic.com/) | JSON logic tree | limited | small libs (many languages) | portable business/boolean rules shared across services |",
    "| [JSON-e](https://json-e.js.org/) | JSON template | limited | JS / Python | parameterising JSON config with interpolation |",
    "| [Jsonnet](https://jsonnet.org/) | full templating language | yes | native binary | generating large config (e.g. Kubernetes) from a real language |",
    "| [json-templates](https://github.com/datavis-tech/json-templates) | JSON with `{{placeholders}}` | no | tiny JS library | simple value substitution into a JSON skeleton |",
    "",
    "**Where `transon` is _not_ the best pick** (worth being honest about):",
    "",
    "- **Expression-heavy** transforms read far more concisely in a string DSL like JSONata or jq — `transon` spells `(a + b) * c` as a nested rule tree.",
    "- **Maturity & ecosystem**: jq and JSONata are battle-tested with large communities; `transon` is young and Python-only.",
    "",
    "### The trade-off, concretely",
    "",
    "The same transform — *multiply each order's `qty` by its `price`* — over input",
    '`{"orders": [{"qty": 2, "price": 3}, {"qty": 5, "price": 7}]}`:',
    "",
    "JSONata — a terse string expression:",
    "",
    "```",
    "orders.(qty * price)",
    "```",
    "",
    "`transon` — pure JSON, composable rules:",
    "",
    "```json",
    "{",
    '  "$": "chain",',
    '  "funcs": [',
    '    {"$": "attr", "name": "orders"},',
    "    {",
    '      "$": "map",',
    '      "item": {',
    '        "$": "expr",',
    '        "op": "mul",',
    '        "values": [',
    '          {"$": "attr", "name": "qty"},',
    '          {"$": "attr", "name": "price"}',
    "        ]",
    "      }",
    "    }",
    "  ]",
    "}",
    "```",
    "",
    "Both yield `[6, 35]`. JSONata wins on brevity; `transon` wins when the template itself must be **data** — stored in a database, generated by another program, reviewed as a diff, checked with `Transformer.validate()`, or extended with your own rules.",
].join("\n");

export function Comparison() {
    return (
        <section>
            <h3 id="comparison">
                <a href="#comparison" className="heading-anchor">transon vs. alternatives</a>
            </h3>
            <Markdown>{COMPARISON_MD}</Markdown>
        </section>
    );
}
